name: "db initd"

on:
  pull_request:
   types:
      - opened
      - synchronize
      - reopened
#  push:
#    branches:
#      - base

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  database_init:
    runs-on: ubuntu-22.04
    container: gentoo/stage3:amd64-systemd
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Dependencies
      run: |
        mkdir /etc/portage/repos.conf
        touch /etc/portage/repos.conf/gentoo.conf
        echo '[gentoo]
        sync-type = webrsync' >> /etc/portage/repos.conf/gentoo.conf
        emerge --sync
        emerge --quiet-build dev-db/mariadb
    - name: Configure mysql and run service
      shell: bash
      run: |
        root | emerge --config dev-db/mariadb
        /bin/sleep 20
        systemctl enable mariadb.service
