name: "mariadb 10.6.11 "

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - base

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  GCC12_64bit:
    runs-on: ubuntu-latest
    container: gentoo/stage3:amd64-systemd
    services:
      mysql:
        image: mariadb:10.6.11
        env:
          MYSQL_DATABASE: xidb
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        echo 'FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox"' >> /etc/portage/make.conf
        mkdir /etc/portage/repos.conf
        touch /etc/portage/repos.conf/gentoo.conf
        echo '[gentoo]
        sync-type = webrsync' >> /etc/portage/repos.conf/gentoo.conf
        emerge --sync
        emerge --quiet-build app-eselect/eselect-repository dev-vcs/git
        eselect repository add claytabase git https://github.com/claybie/claytabase.git
        eselect repository enable guru
        emaint sync -r claytabase
        emaint sync -r guru
        touch /etc/portage/package.accept_keywords/mariadb-connector-c
        touch /etc/portage/package.accept_keywords/mariadb-connector-python
        echo '=dev-db/mariadb-connector-c-3.3.4 ~amd64' >> /etc/portage/package.accept_keywords/mariadb-connector-c
        echo '=dev-python/mariadb-1.1.6 ~amd64' >> /etc/portage/package.accept_keywords/mariadb-connector-python
        emerge --quiet-build dev-db/mariadb dev-lang/luajit net-libs/zeromq dev-python/black dev-python/colorama dev-python/GitPython dev-python/mariadb dev-python/pylint dev-python/pyyaml dev-python/pyzmq dev-python/regex
    #- name: Cache 'build' folder
    #  uses: actions/cache@v3
    #  with:
    #    path: build
    #    key: ${{ runner.os }}-gcc
    - name: Configure CMake
      run: |
        export CC=/usr/bin/gcc-12
        export CXX=/usr/bin/g++-12
        mkdir -p build
        CFLAGS=-m64 CXXFLAGS=-m64 LDFLAGS=-m64 cmake -S . -B build
    - name: Build
      run: |
        cmake --build build -j4
    - name: Verify MySQL connection from container
      run: |
        mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES"
    - name: Import SQL files
      run: |
        for f in sql/*.sql; do
          echo -e "Importing $f into the database..."
          mysql xidb -h 127.0.0.1 -uroot -proot < $f
        done
        mysql xidb -h 127.0.0.1 -uroot -proot -e "SHOW tables"
    - name: Copy settings
      run: |
        cp settings/default/* settings/
    - name: Enable Modules
      shell: bash
      run: |
        python3 << EOF
        with open("modules/init.txt", "w") as f:
            f.write("custom\n")
            f.write("era\n")
            f.write("renamer\n")
        EOF
    - name: Startup and character login checks
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 3
        retry_on: timeout
        shell: bash
        command: |
          chmod +x xi_connect
          chmod +x xi_map
          chmod +x xi_search
          chmod +x xi_world
          ls -l

          printf "\nStart server processes\n"
          screen -d -m -S xi_connect ./xi_connect --log login-server.log
          screen -d -m -S xi_search ./xi_search --log search-server.log
          screen -d -m -S xi_map ./xi_map --log map-server.log
          screen -d -m -S xi_world ./xi_world --log world-server.log

          printf "\nWaiting 5m for servers to fully start up\n"
          sleep 300s

          printf "\nPopulating database\n"
          mysql xidb -h 127.0.0.1 -uroot -proot << EOF
          -- Clean out anything already there (just in case)
          DELETE FROM accounts;
          DELETE FROM chars;
          -- Create an account
          INSERT INTO accounts(id, login, password, timecreate, timelastmodify, status, priv)
          VALUES(1000, 'admin', PASSWORD('admin'), NOW(), NOW(), 1, 1);
          SELECT id, login FROM accounts;
          -- Create a character
          INSERT INTO chars(charid, accid, charname, pos_zone, nation, gmlevel)
          VALUES(1, 1000, 'Test', 0, 0, 5);
          -- Set char_look (default is 0 and trips up scripting)
          INSERT INTO char_look (charid, face, race, size, head, body, hands, legs, feet, main, sub, ranged)
          VALUES (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
          SELECT charid, face, race FROM char_look;
          -- Update character information
          -- Place near some Robber Crabs in Kuftal Tunnel
          UPDATE chars
          SET
              pos_zone = 174,
              pos_prevzone = 174,
              pos_x = 55,
              pos_y = -9,
              pos_z = -140
          WHERE charid = 1;
          SELECT charid, accid, pos_zone, pos_x, pos_y, pos_z FROM chars;
          -- Set GodMode CharVar = 1
          INSERT INTO char_vars(charid, varname, value)
          VALUES(1, 'GodMode', 1);
          SELECT * FROM char_vars;
          EOF

          printf "\nRunning HeadlessXI for 60 seconds\n"
          python3 << EOF
          import time
          from tools.headlessxi.hxiclient import HXIClient
          hxi_client = HXIClient('admin', 'admin', 'localhost')
          hxi_client.login()
          print('Sleeping 30s')
          time.sleep(30)
          hxi_client.logout()
          EOF

          killall screen
    - name: Check for errors and warnings
      if: ${{ success() || failure() }}
      run: |
        cat login-server*.log
        cat map-server*.log
        cat search-server*.log
        cat world-server*.log

        if grep -qi "warning\|error\|crash" login-server*.log; then
            exit -1
        fi

        if grep -qi "warning\|error\|crash" map-server*.log; then
            exit -1
        fi

        if grep -qi "warning\|error\|crash" search-server*.log; then
            exit -1
        fi

        if grep -qi "warning\|error\|crash" world-server*.log; then
            exit -1
        fi
